version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=clinical_takehome_dev
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5444:5432"